---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: No pueden instanciarse objetos de una clase abstracta
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Una clase abstracta debe tener únicamente métodos abstractos
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`Jefe` y `Pasante` implementarán la interfaz `Empleado`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`Jefe` y `Pasante` heredarán de la clase abstracta `Empleado`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: El método `trabajar` estará definido en `Empleado`
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: El método `trabajar` estará definido en `Jefe` y `Pasante`
  checked: false
name: Clase abstracta
